// Generated by PlutoniX project-agent registry.
// This file keeps managed app projects related to their project-scoped agents.
MERGE (:Agent {id: 'plutonix-fullstack-agent', name: 'PlutoniX Fullstack Agent', role: 'global-orchestrator', status: 'active'})
MERGE (:Agent {id: 'plutonix-independent-reviewer', name: 'PlutoniX Independent Reviewer', role: 'reviewer', status: 'available', read_only: true})
MATCH (o:Agent {id: 'plutonix-fullstack-agent'}), (r:Agent {id: 'plutonix-independent-reviewer'}) MERGE (o)-[:MAY_REQUEST_REVIEW_FROM {adaptive: true}]->(r)

MERGE (p:Project {id: 'project:agenticongen-9TUSjQ'})
SET p.name = "AgentIconGen", p.folder_name = "agenticongen", p.workspace_dir = "/workspace/money/apps/agenticongen", p.port = 5302
MERGE (a:Agent {id: "agenticongen-orchestrator-agent"})
SET a.name = "Agenticongen Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "agenticongen-9TUSjQ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "agenticongen-ui-composition-agent"})
SET a.name = "Agenticongen UI Composition Agent", a.role = "ui-composition", a.project_id = "agenticongen-9TUSjQ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "agenticongen-content-data-agent"})
SET a.name = "Agenticongen Content Data Agent", a.role = "content-data", a.project_id = "agenticongen-9TUSjQ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "agenticongen-runtime-packaging-agent"})
SET a.name = "Agenticongen Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "agenticongen-9TUSjQ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:agenticongen-9TUSjQ'}), (a:Agent {id: "agenticongen-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "agenticongen-orchestrator-agent"}), (b:Agent {id: "agenticongen-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "agenticongen-orchestrator-agent"}), (b:Agent {id: "agenticongen-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "agenticongen-orchestrator-agent"}), (b:Agent {id: "agenticongen-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:bag-commerce-studio-Tj4bB8'})
SET p.name = "adX", p.folder_name = "adx", p.workspace_dir = "/workspace/money/apps/adx", p.port = 5316
MERGE (a:Agent {id: "adx-orchestrator-agent"})
SET a.name = "AdX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "adx-qagent-controller"})
SET a.name = "AdX QAgent Controller", a.role = "qagent-controller", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "adx-experience-composition-agent"})
SET a.name = "AdX Experience Composition Agent", a.role = "experience-composition", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "adx-data-contract-agent"})
SET a.name = "AdX Data Contract Agent", a.role = "data-contract", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "adx-runtime-packaging-agent"})
SET a.name = "AdX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "adx-media-asset-agent"})
SET a.name = "AdX Media Asset Agent", a.role = "media-asset", a.project_id = "bag-commerce-studio-Tj4bB8", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "adx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:bag-commerce-studio-Tj4bB8'}), (a:Agent {id: "adx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "adx-orchestrator-agent"}), (b:Agent {id: "adx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "adx-orchestrator-agent"}), (b:Agent {id: "adx-experience-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "adx-orchestrator-agent"}), (b:Agent {id: "adx-data-contract-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "adx-orchestrator-agent"}), (b:Agent {id: "adx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "adx-orchestrator-agent"}), (b:Agent {id: "adx-media-asset-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:bag-commerce-studio-y2obrr'})
SET p.name = "VirtuX", p.folder_name = "virtux", p.workspace_dir = "/workspace/money/apps/virtux", p.port = 5310
MERGE (a:Agent {id: "virtux-orchestrator-agent"})
SET a.name = "VirtuX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "bag-commerce-studio-y2obrr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "virtux-qagent-controller"})
SET a.name = "VirtuX QAgent Controller", a.role = "qagent-controller", a.project_id = "bag-commerce-studio-y2obrr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "virtux-ui-composition-agent"})
SET a.name = "VirtuX UI Composition Agent", a.role = "ui-composition", a.project_id = "bag-commerce-studio-y2obrr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "virtux-content-data-agent"})
SET a.name = "VirtuX Content Data Agent", a.role = "content-data", a.project_id = "bag-commerce-studio-y2obrr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "virtux-runtime-packaging-agent"})
SET a.name = "VirtuX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "bag-commerce-studio-y2obrr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "virtux-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:bag-commerce-studio-y2obrr'}), (a:Agent {id: "virtux-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "virtux-orchestrator-agent"}), (b:Agent {id: "virtux-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "virtux-orchestrator-agent"}), (b:Agent {id: "virtux-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "virtux-orchestrator-agent"}), (b:Agent {id: "virtux-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "virtux-orchestrator-agent"}), (b:Agent {id: "virtux-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:brushx-zHXT8q'})
SET p.name = "BrushX", p.folder_name = "brushx", p.workspace_dir = "/workspace/money/apps/brushx", p.port = 5313
MERGE (a:Agent {id: "brushx-orchestrator-agent"})
SET a.name = "BrushX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "brushx-qagent-controller"})
SET a.name = "BrushX QAgent Controller", a.role = "qagent-controller", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "brushx-experience-composition-agent"})
SET a.name = "BrushX Experience Composition Agent", a.role = "experience-composition", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "brushx-data-contract-agent"})
SET a.name = "BrushX Data Contract Agent", a.role = "data-contract", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "brushx-runtime-packaging-agent"})
SET a.name = "BrushX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "brushx-media-asset-agent"})
SET a.name = "BrushX Media Asset Agent", a.role = "media-asset", a.project_id = "brushx-zHXT8q", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "brushx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:brushx-zHXT8q'}), (a:Agent {id: "brushx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "brushx-orchestrator-agent"}), (b:Agent {id: "brushx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "brushx-orchestrator-agent"}), (b:Agent {id: "brushx-experience-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "brushx-orchestrator-agent"}), (b:Agent {id: "brushx-data-contract-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "brushx-orchestrator-agent"}), (b:Agent {id: "brushx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "brushx-orchestrator-agent"}), (b:Agent {id: "brushx-media-asset-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:cvmakerx-e4XAzI'})
SET p.name = "CVMakerX", p.folder_name = "cvmakerx", p.workspace_dir = "/workspace/money/apps/cvmakerx", p.port = 5300
MERGE (a:Agent {id: "cvmakerx-orchestrator-agent"})
SET a.name = "CVMakerX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "cvmakerx-e4XAzI", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "cvmakerx-qagent-controller"})
SET a.name = "CVMakerX QAgent Controller", a.role = "qagent-controller", a.project_id = "cvmakerx-e4XAzI", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "cvmakerx-artifact-production-agent"})
SET a.name = "CVMakerX Artifact Production Agent", a.role = "artifact-production", a.project_id = "cvmakerx-e4XAzI", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "cvmakerx-runtime-packaging-agent"})
SET a.name = "CVMakerX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "cvmakerx-e4XAzI", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "cvmakerx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:cvmakerx-e4XAzI'}), (a:Agent {id: "cvmakerx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "cvmakerx-orchestrator-agent"}), (b:Agent {id: "cvmakerx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "cvmakerx-orchestrator-agent"}), (b:Agent {id: "cvmakerx-artifact-production-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "cvmakerx-orchestrator-agent"}), (b:Agent {id: "cvmakerx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:databricksx-n7lCNf'})
SET p.name = "DatabricksX", p.folder_name = "databricksx", p.workspace_dir = "/workspace/money/apps/databricksx", p.port = 5317
MERGE (a:Agent {id: "databricksx-orchestrator-agent"})
SET a.name = "DatabricksX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "databricksx-n7lCNf", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "databricksx-qagent-controller"})
SET a.name = "DatabricksX QAgent Controller", a.role = "qagent-controller", a.project_id = "databricksx-n7lCNf", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "databricksx-experience-composition-agent"})
SET a.name = "DatabricksX Experience Composition Agent", a.role = "experience-composition", a.project_id = "databricksx-n7lCNf", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "databricksx-data-contract-agent"})
SET a.name = "DatabricksX Data Contract Agent", a.role = "data-contract", a.project_id = "databricksx-n7lCNf", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "databricksx-runtime-packaging-agent"})
SET a.name = "DatabricksX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "databricksx-n7lCNf", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "databricksx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:databricksx-n7lCNf'}), (a:Agent {id: "databricksx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "databricksx-orchestrator-agent"}), (b:Agent {id: "databricksx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "databricksx-orchestrator-agent"}), (b:Agent {id: "databricksx-experience-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "databricksx-orchestrator-agent"}), (b:Agent {id: "databricksx-data-contract-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "databricksx-orchestrator-agent"}), (b:Agent {id: "databricksx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:geofinderx-2yFsDY'})
SET p.name = "GeoFinderX", p.folder_name = "geofinderx", p.workspace_dir = "/workspace/money/apps/geofinderx", p.port = 5300
MERGE (a:Agent {id: "geofinderx-orchestrator-agent"})
SET a.name = "Geofinderx Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-ui-composition-agent"})
SET a.name = "Geofinderx UI Composition Agent", a.role = "ui-composition", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-content-data-agent"})
SET a.name = "Geofinderx Content Data Agent", a.role = "content-data", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-runtime-packaging-agent"})
SET a.name = "Geofinderx Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:geofinderx-2yFsDY'}), (a:Agent {id: "geofinderx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:gymx-9JXKDV'})
SET p.name = "GymX", p.folder_name = "gymx", p.workspace_dir = "/workspace/money/apps/gymx", p.port = 5315
MERGE (a:Agent {id: "gymx-orchestrator-agent"})
SET a.name = "GymX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-qagent-controller"})
SET a.name = "GymX QAgent Controller", a.role = "qagent-controller", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-experience-composition-agent"})
SET a.name = "GymX Experience Composition Agent", a.role = "experience-composition", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-data-contract-agent"})
SET a.name = "GymX Data Contract Agent", a.role = "data-contract", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-runtime-packaging-agent"})
SET a.name = "GymX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-application-architecture-agent"})
SET a.name = "GymX Application Architecture Agent", a.role = "application-architecture", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-governance-security-agent"})
SET a.name = "GymX Governance and Security Agent", a.role = "governance-security", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "gymx-media-asset-agent"})
SET a.name = "GymX Media Asset Agent", a.role = "media-asset", a.project_id = "gymx-9JXKDV", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "gymx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:gymx-9JXKDV'}), (a:Agent {id: "gymx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-experience-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-data-contract-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-application-architecture-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-governance-security-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "gymx-orchestrator-agent"}), (b:Agent {id: "gymx-media-asset-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:investmentfinderx-z8rTq_'})
SET p.name = "InvestmentFinderX", p.folder_name = "investmentfinderx", p.workspace_dir = "/workspace/money/apps/investmentfinderx", p.port = 5303
MERGE (a:Agent {id: "investmentfinderx-orchestrator-agent"})
SET a.name = "Investmentfinderx Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "investmentfinderx-z8rTq_", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "investmentfinderx-qagent-controller"})
SET a.name = "Investmentfinderx QAgent Controller", a.role = "qagent-controller", a.project_id = "investmentfinderx-z8rTq_", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "investmentfinderx-ui-composition-agent"})
SET a.name = "Investmentfinderx UI Composition Agent", a.role = "ui-composition", a.project_id = "investmentfinderx-z8rTq_", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "investmentfinderx-content-data-agent"})
SET a.name = "Investmentfinderx Content Data Agent", a.role = "content-data", a.project_id = "investmentfinderx-z8rTq_", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "investmentfinderx-runtime-packaging-agent"})
SET a.name = "Investmentfinderx Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "investmentfinderx-z8rTq_", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:investmentfinderx-z8rTq_'}), (a:Agent {id: "investmentfinderx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "investmentfinderx-orchestrator-agent"}), (b:Agent {id: "investmentfinderx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "investmentfinderx-orchestrator-agent"}), (b:Agent {id: "investmentfinderx-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "investmentfinderx-orchestrator-agent"}), (b:Agent {id: "investmentfinderx-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "investmentfinderx-orchestrator-agent"}), (b:Agent {id: "investmentfinderx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:mapex-M6rGkR'})
SET p.name = "mapEx", p.folder_name = "mapex", p.workspace_dir = "/workspace/money/mapex", p.port = 5301
MERGE (a:Agent {id: "mapex-orchestrator-agent"})
SET a.name = "Mapex Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-ui-composition-agent"})
SET a.name = "Mapex UI Composition Agent", a.role = "ui-composition", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-content-data-agent"})
SET a.name = "Mapex Content Data Agent", a.role = "content-data", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-runtime-packaging-agent"})
SET a.name = "Mapex Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:mapex-M6rGkR'}), (a:Agent {id: "mapex-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:mentalheathcounselor-PJ1N2o'})
SET p.name = "MentalHeathCounselor", p.folder_name = "mentalheathcounselor", p.workspace_dir = "/workspace/money/apps/mentalheathcounselor", p.port = 5311
MERGE (a:Agent {id: "mentalheathcounselor-orchestrator-agent"})
SET a.name = "MentalHeathCounselor Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "mentalheathcounselor-PJ1N2o", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mentalheathcounselor-qagent-controller"})
SET a.name = "MentalHeathCounselor QAgent Controller", a.role = "qagent-controller", a.project_id = "mentalheathcounselor-PJ1N2o", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mentalheathcounselor-ui-composition-agent"})
SET a.name = "MentalHeathCounselor UI Composition Agent", a.role = "ui-composition", a.project_id = "mentalheathcounselor-PJ1N2o", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mentalheathcounselor-content-data-agent"})
SET a.name = "MentalHeathCounselor Content Data Agent", a.role = "content-data", a.project_id = "mentalheathcounselor-PJ1N2o", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mentalheathcounselor-runtime-packaging-agent"})
SET a.name = "MentalHeathCounselor Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "mentalheathcounselor-PJ1N2o", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "mentalheathcounselor-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:mentalheathcounselor-PJ1N2o'}), (a:Agent {id: "mentalheathcounselor-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "mentalheathcounselor-orchestrator-agent"}), (b:Agent {id: "mentalheathcounselor-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "mentalheathcounselor-orchestrator-agent"}), (b:Agent {id: "mentalheathcounselor-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mentalheathcounselor-orchestrator-agent"}), (b:Agent {id: "mentalheathcounselor-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mentalheathcounselor-orchestrator-agent"}), (b:Agent {id: "mentalheathcounselor-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:researchanddevx-xF8SDs'})
SET p.name = "ResearchAndDevX", p.folder_name = "researchanddevx", p.workspace_dir = "/workspace/money/apps/researchanddevx", p.port = 5309
MERGE (a:Agent {id: "researchanddevx-orchestrator-agent"})
SET a.name = "Researchanddevx Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "researchanddevx-xF8SDs", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "researchanddevx-qagent-controller"})
SET a.name = "Researchanddevx QAgent Controller", a.role = "qagent-controller", a.project_id = "researchanddevx-xF8SDs", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "researchanddevx-ui-composition-agent"})
SET a.name = "Researchanddevx UI Composition Agent", a.role = "ui-composition", a.project_id = "researchanddevx-xF8SDs", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "researchanddevx-content-data-agent"})
SET a.name = "Researchanddevx Content Data Agent", a.role = "content-data", a.project_id = "researchanddevx-xF8SDs", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "researchanddevx-runtime-packaging-agent"})
SET a.name = "Researchanddevx Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "researchanddevx-xF8SDs", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "researchanddevx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:researchanddevx-xF8SDs'}), (a:Agent {id: "researchanddevx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "researchanddevx-orchestrator-agent"}), (b:Agent {id: "researchanddevx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "researchanddevx-orchestrator-agent"}), (b:Agent {id: "researchanddevx-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "researchanddevx-orchestrator-agent"}), (b:Agent {id: "researchanddevx-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "researchanddevx-orchestrator-agent"}), (b:Agent {id: "researchanddevx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:spydash-qkWtmJ'})
SET p.name = "spyDash", p.folder_name = "spydash", p.workspace_dir = "/workspace/money/apps/spydash", p.port = 5307
MERGE (a:Agent {id: "spydash-orchestrator-agent"})
SET a.name = "Spydash Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "spydash-qagent-controller"})
SET a.name = "Spydash QAgent Controller", a.role = "qagent-controller", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "spydash-ui-composition-agent"})
SET a.name = "Spydash UI Composition Agent", a.role = "ui-composition", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "spydash-content-data-agent"})
SET a.name = "Spydash Content Data Agent", a.role = "content-data", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "spydash-runtime-packaging-agent"})
SET a.name = "Spydash Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "spydash-analytics-dashboard-agent"})
SET a.name = "Spydash Analytics Dashboard Agent", a.role = "analytics-dashboard", a.project_id = "spydash-qkWtmJ", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "spydash-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:spydash-qkWtmJ'}), (a:Agent {id: "spydash-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "spydash-orchestrator-agent"}), (b:Agent {id: "spydash-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "spydash-orchestrator-agent"}), (b:Agent {id: "spydash-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "spydash-orchestrator-agent"}), (b:Agent {id: "spydash-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "spydash-orchestrator-agent"}), (b:Agent {id: "spydash-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "spydash-orchestrator-agent"}), (b:Agent {id: "spydash-analytics-dashboard-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:videopresentationforproductx-GtDUxv'})
SET p.name = "VideoPresentationForProductX", p.folder_name = "videopresentationforproductx", p.workspace_dir = "/workspace/money/apps/videopresentationforproductx", p.port = 5311
MERGE (a:Agent {id: "videopresentationforproductx-orchestrator-agent"})
SET a.name = "VideoPresentationForProductX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "videopresentationforproductx-qagent-controller"})
SET a.name = "VideoPresentationForProductX QAgent Controller", a.role = "qagent-controller", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "videopresentationforproductx-ui-composition-agent"})
SET a.name = "VideoPresentationForProductX UI Composition Agent", a.role = "ui-composition", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "videopresentationforproductx-content-data-agent"})
SET a.name = "VideoPresentationForProductX Content Data Agent", a.role = "content-data", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "videopresentationforproductx-runtime-packaging-agent"})
SET a.name = "VideoPresentationForProductX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "videopresentationforproductx-analytics-dashboard-agent"})
SET a.name = "VideoPresentationForProductX Analytics Dashboard Agent", a.role = "analytics-dashboard", a.project_id = "videopresentationforproductx-GtDUxv", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "videopresentationforproductx-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:videopresentationforproductx-GtDUxv'}), (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}), (b:Agent {id: "videopresentationforproductx-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}), (b:Agent {id: "videopresentationforproductx-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}), (b:Agent {id: "videopresentationforproductx-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}), (b:Agent {id: "videopresentationforproductx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "videopresentationforproductx-orchestrator-agent"}), (b:Agent {id: "videopresentationforproductx-analytics-dashboard-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:voicex-4q9G58'})
SET p.name = "voiceX", p.folder_name = "voicex", p.workspace_dir = "/workspace/money/apps/voicex", p.port = 5314
MERGE (a:Agent {id: "voicex-orchestrator-agent"})
SET a.name = "VoiceX Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "voicex-4q9G58", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "voicex-qagent-controller"})
SET a.name = "VoiceX QAgent Controller", a.role = "qagent-controller", a.project_id = "voicex-4q9G58", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "voicex-experience-composition-agent"})
SET a.name = "VoiceX Experience Composition Agent", a.role = "experience-composition", a.project_id = "voicex-4q9G58", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "voicex-data-contract-agent"})
SET a.name = "VoiceX Data Contract Agent", a.role = "data-contract", a.project_id = "voicex-4q9G58", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "voicex-runtime-packaging-agent"})
SET a.name = "VoiceX Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "voicex-4q9G58", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "voicex-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:voicex-4q9G58'}), (a:Agent {id: "voicex-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "voicex-orchestrator-agent"}), (b:Agent {id: "voicex-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "voicex-orchestrator-agent"}), (b:Agent {id: "voicex-experience-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "voicex-orchestrator-agent"}), (b:Agent {id: "voicex-data-contract-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "voicex-orchestrator-agent"}), (b:Agent {id: "voicex-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:webforbusinesses-xu7qsM'})
SET p.name = "WebForBusinesses", p.folder_name = "webforbusinesses", p.workspace_dir = "/workspace/money/apps/webforbusinesses", p.port = 5308
MERGE (a:Agent {id: "webforbusinesses-orchestrator-agent"})
SET a.name = "Webforbusinesses Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "webforbusinesses-xu7qsM", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "webforbusinesses-qagent-controller"})
SET a.name = "Webforbusinesses QAgent Controller", a.role = "qagent-controller", a.project_id = "webforbusinesses-xu7qsM", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "webforbusinesses-ui-composition-agent"})
SET a.name = "Webforbusinesses UI Composition Agent", a.role = "ui-composition", a.project_id = "webforbusinesses-xu7qsM", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "webforbusinesses-content-data-agent"})
SET a.name = "Webforbusinesses Content Data Agent", a.role = "content-data", a.project_id = "webforbusinesses-xu7qsM", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "webforbusinesses-runtime-packaging-agent"})
SET a.name = "Webforbusinesses Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "webforbusinesses-xu7qsM", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "webforbusinesses-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:webforbusinesses-xu7qsM'}), (a:Agent {id: "webforbusinesses-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "webforbusinesses-orchestrator-agent"}), (b:Agent {id: "webforbusinesses-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "webforbusinesses-orchestrator-agent"}), (b:Agent {id: "webforbusinesses-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "webforbusinesses-orchestrator-agent"}), (b:Agent {id: "webforbusinesses-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "webforbusinesses-orchestrator-agent"}), (b:Agent {id: "webforbusinesses-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:whatsappmediaanalyser-oAeSvn'})
SET p.name = "WhatsappMediaAnalyser", p.folder_name = "whatsappmediaanalyser", p.workspace_dir = "/workspace/money/apps/whatsappmediaanalyser", p.port = 5304
MERGE (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"})
SET a.name = "Whatsappmediaanalyser Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "whatsappmediaanalyser-oAeSvn", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "whatsappmediaanalyser-qagent-controller"})
SET a.name = "Whatsappmediaanalyser QAgent Controller", a.role = "qagent-controller", a.project_id = "whatsappmediaanalyser-oAeSvn", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "whatsappmediaanalyser-ui-composition-agent"})
SET a.name = "Whatsappmediaanalyser UI Composition Agent", a.role = "ui-composition", a.project_id = "whatsappmediaanalyser-oAeSvn", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "whatsappmediaanalyser-content-data-agent"})
SET a.name = "Whatsappmediaanalyser Content Data Agent", a.role = "content-data", a.project_id = "whatsappmediaanalyser-oAeSvn", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "whatsappmediaanalyser-runtime-packaging-agent"})
SET a.name = "Whatsappmediaanalyser Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "whatsappmediaanalyser-oAeSvn", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "plutonix-fullstack-agent"}), (b:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:whatsappmediaanalyser-oAeSvn'}), (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}), (b:Agent {id: "whatsappmediaanalyser-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}), (b:Agent {id: "whatsappmediaanalyser-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}), (b:Agent {id: "whatsappmediaanalyser-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "whatsappmediaanalyser-orchestrator-agent"}), (b:Agent {id: "whatsappmediaanalyser-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

