import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createDecisionContinuityStore } from "../src/decisionContinuity.js";
import { SuggestionIntelGovernance } from "../src/suggestionIntelGovernance.js";

const tenantId = "suggestion-tenant", workspaceId = "suggestion-workspace", author = { type: "user", id: "author" }, reviewer = { type: "user", id: "reviewer" };
const expiry = "2027-01-01T00:00:00.000Z";
function suggestion(branchId, eventId, overrides = {}) { return { objective: "Review the verified recovery capability gap.", affected: { branchId, qagentRunId: "qagent_fixture" }, triggeringEventId: eventId, triggeringEvidenceIds: ["evidence_fixture"], whatChanged: "A trusted constraint event cleared the recovery blocker.", remainingBlockers: [], expectedBenefit: "A safer recovery decision can be evaluated.", cost: { estimateUsd: 0, basis: "fixture" }, risk: "low", reversibility: "bounded", proposedAction: { kind: "bounded_review_action", summary: "Prepare an isolated candidate for governed review." }, successCondition: "Independent evaluation and human approval pass.", expiresAt: expiry, deduplication: { key: `suggestion:${branchId}`, method: "deterministic-token-jaccard/v1", modelVersion: "fixture/v1", threshold: 0.9 }, modelRationale: "model rationale is untrusted", ...overrides }; }
function intel(branchId) { return { title: "Add verified recovery capability", objective: "Address repeated verified recovery failures.", trigger: { kind: "repeated_failure", evidenceIds: ["incident-1"], frequency: 3, severity: "high" }, affected: { branchId }, reuseDecision: { decision: "create", searches: ["local_registry", "transactional_ledger", "graph_projection", "authorized_vector_index"].map((source) => ({ source, query: "recovery capability", resultRefs: source === "local_registry" ? ["existing-readonly-tool"] : [] })), whyReuseUnsuitable: "Existing registered capability is read-only and cannot meet the measured recovery requirement." }, dependencies: ["review"], permissions: ["none until approved"], data: "tenant-scoped operational metadata", infrastructure: "existing governed runtime", risks: { licence: "review required", security: "isolated candidate required", privacy: "no prompt retention" }, cost: { implementationUsd: 0, operatingUsdMonthly: 0, basis: "fixture" }, acceptanceTests: ["deterministic fixture passes"], metrics: ["recovery success rate"], rollout: "bounded canary", monitoring: "tenant metrics", rollback: "Step 4 rollback", ownerApprovalRequired: true, deduplication: { key: `intel:${branchId}`, method: "deterministic-token-jaccard/v1", modelVersion: "fixture/v1", threshold: 0.9 }, modelRationale: "untrusted rationale" }; }
async function seeded(context) { const root = await fs.mkdtemp(path.join(os.tmpdir(), "plutonix-suggestion-")); context.after(() => fs.rm(root, { recursive: true, force: true })); const store = createDecisionContinuityStore({ root, reconsiderationCooldownMs: 0 }); const branch = await store.createBranch({ workspaceId, decisionId: "suggestion-decision", objective: "Recover safely.", producedBy: { agentId: "planner", actorId: author.id }, constraintExpression: { constraintId: "recovery" }, revisitTriggers: ["recovery"], candidate: { strategy: "safe" } }, { tenantId, actor: author }); await store.setDisposition({ branchId: branch.id, status: "deferred" }, { tenantId, actor: author }); const event = await store.ingestConditionEvent({ eventId: "trusted-clear", workspaceId, source: "monitor", observations: [{ constraintId: "recovery", state: "cleared", source: "monitor", trusted: true, authorized: true }] }, { tenantId, actor: { type: "service", id: "monitor" } }); return { service: new SuggestionIntelGovernance({ store }), branch, event }; }

test("cleared constraints create one evidence-linked suggestion and duplicate events deduplicate", async (context) => { const { service, branch } = await seeded(context); const first = await service.createSuggestion(suggestion(branch.id, "trusted-clear"), { tenantId, workspaceId, actor: author }); const second = await service.createSuggestion(suggestion(branch.id, "trusted-clear"), { tenantId, workspaceId, actor: author }); assert.equal(first.status, "created"); assert.equal(second.status, "deduplicated"); assert.equal(first.suggestion.authoritativeFacts.triggerEventId, "trusted-clear"); });
test("blockers prevent lifecycle entry, edits invalidate review, and rejected/expired records remain queryable", async (context) => { const { service, branch } = await seeded(context); const created = await service.createSuggestion(suggestion(branch.id, "trusted-clear", { remainingBlockers: ["licence review"] }), { tenantId, workspaceId, actor: author }); await assert.rejects(() => service.reviewSuggestion({ suggestionId: created.suggestion.id, decision: "ready_for_approval", evaluationDigest: "e".repeat(64) }, { tenantId, workspaceId, actor: reviewer }), (error) => error.code === "remaining_blockers"); const edited = await service.editSuggestion({ suggestionId: created.suggestion.id, patch: suggestion(branch.id, "trusted-clear", { whatChanged: "Materially changed bounded action." }), reason: "New evidence" }, { tenantId, workspaceId, actor: author }); assert.equal(edited.policyState, "invalidated"); const rejected = await service.reviewSuggestion({ suggestionId: created.suggestion.id, decision: "rejected" }, { tenantId, workspaceId, actor: reviewer }); const expired = await service.createSuggestion(suggestion(branch.id, "trusted-clear", { expiresAt: "2020-01-01T00:00:00.000Z", deduplication: { ...suggestion(branch.id, "trusted-clear").deduplication, key: "expired-suggestion" } }), { tenantId, workspaceId, actor: author }); assert.equal(rejected.state, "rejected"); assert.equal(expired.suggestion.state, "expired"); assert.equal((await service.list({ tenantId, workspaceId })).length, 2); });
test("Intel records all reuse sources and refuses duplicate/new capability without reuse rationale", async (context) => { const { service, branch } = await seeded(context); const created = await service.createIntelProposal(intel(branch.id), { tenantId, workspaceId, actor: author }); const duplicate = await service.createIntelProposal(intel(branch.id), { tenantId, workspaceId, actor: author }); assert.equal(created.proposal.reuseDecision.searches.length, 4); assert.equal(duplicate.status, "deduplicated"); await assert.rejects(() => service.createIntelProposal({ ...intel(branch.id), reuseDecision: { ...intel(branch.id).reuseDecision, whyReuseUnsuitable: "" }, deduplication: { ...intel(branch.id).deduplication, key: "intel:missing-rationale" } }, { tenantId, workspaceId, actor: author }), (error) => error.code === "reuse_rationale_required"); });
test("suggestion has no direct install, permission, flag, or deployment method and cross-tenant links fail", async (context) => { const { service, branch } = await seeded(context); const created = await service.createSuggestion(suggestion(branch.id, "trusted-clear"), { tenantId, workspaceId, actor: author }); assert.equal(typeof service.deploy, "undefined"); assert.equal(typeof service.grantPermission, "undefined"); await assert.rejects(() => service.createSuggestion(suggestion(branch.id, "trusted-clear", { deduplication: { ...suggestion(branch.id, "trusted-clear").deduplication, key: "cross-tenant-key" } }), { tenantId: "other", workspaceId, actor: author }), (error) => error.code === "trigger_not_found"); await service.reviewSuggestion({ suggestionId: created.suggestion.id, decision: "ready_for_approval", evaluationDigest: "e".repeat(64) }, { tenantId, workspaceId, actor: reviewer }); const linked = await service.linkGovernedPromotion({ suggestionId: created.suggestion.id, promotionRequestId: "gpr_fixture", approvalDigest: "a".repeat(64) }, { tenantId, workspaceId, actor: reviewer }); assert.equal(linked.lifecycleLinks[0].promotionRequestId, "gpr_fixture"); });
