import crypto from "node:crypto";
import { z } from "zod";
import { DecisionContinuityError } from "./decisionContinuity.js";

export const SUGGESTION_STATES = Object.freeze(["informational", "needs_evidence", "ready_for_review", "ready_for_approval", "approved_for_execution", "rejected", "expired", "superseded", "completed"]);
const ACTIVE = new Set(["informational", "needs_evidence", "ready_for_review", "ready_for_approval", "approved_for_execution"]);
const now = () => new Date().toISOString();
const copy = (value) => JSON.parse(JSON.stringify(value));
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.keys(value).sort().reduce((out, key) => ({ ...out, [key]: canonical(value[key]) }), {}) : value;
const digest = (value) => crypto.createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");
const safeText = (value, limit = 1200) => String(value || "").replace(/(?:authorization|bearer|token|password|secret)\s*[:=]\s*[^\s,;]+/gi, "<redacted>").slice(0, limit);
function scope(record, tenantId, workspaceId) { if (!record || record.tenantId !== tenantId || record.workspaceId !== workspaceId) throw new DecisionContinuityError("The requested governed suggestion is unavailable in this tenant scope.", { code: "not_found", status: 404 }); }
function audit({ tenantId, workspaceId, type, actor, correlationId, payload }) { return { id: id("dce"), schemaVersion: "suggestion-intel/v1", tenantId, workspaceId, type, occurredAt: now(), actor: actor || { type: "service", id: "suggestion-intel" }, correlationId: correlationId || null, payload: copy(payload) }; }
function ensure(state) { state.governedSuggestions ||= {}; state.intelCapabilityProposals ||= {}; }
const LinkSchema = z.object({ branchId: z.string().max(160).optional(), capabilityId: z.string().max(160).optional(), changeId: z.string().max(160).optional(), qagentRunId: z.string().max(160).optional(), brainxRouteId: z.string().max(160).optional(), promotionRequestId: z.string().max(160).optional(), executionId: z.string().max(160).optional(), canaryId: z.string().max(160).optional(), outcomeId: z.string().max(160).optional(), rollbackId: z.string().max(160).optional() }).strict();
const SuggestionSchema = z.object({ objective: z.string().min(8).max(1200), affected: LinkSchema, triggeringEventId: z.string().min(1).max(240), triggeringEvidenceIds: z.array(z.string().min(1).max(160)).min(1).max(32), whatChanged: z.string().min(3).max(2000), remainingBlockers: z.array(z.string().min(1).max(600)).max(24).default([]), expectedBenefit: z.string().min(3).max(1000), cost: z.object({ estimateUsd: z.number().min(0).max(100000), basis: z.string().min(1).max(400) }).strict(), risk: z.enum(["low", "medium", "high", "critical"]), reversibility: z.enum(["easy", "bounded", "hard", "unknown"]), proposedAction: z.object({ kind: z.enum(["bounded_review_action", "governed_promotion_reference"]), summary: z.string().min(3).max(1600) }).strict(), successCondition: z.string().min(3).max(1000), expiresAt: z.string().datetime(), deduplication: z.object({ key: z.string().min(8).max(240), method: z.literal("deterministic-token-jaccard/v1"), modelVersion: z.string().min(1).max(120), threshold: z.number().min(0).max(1) }).strict(), modelRationale: z.string().max(2000).default("") }).strict();
const IntelSchema = z.object({ title: z.string().min(8).max(500), objective: z.string().min(8).max(1200), trigger: z.object({ kind: z.enum(["repeated_failure", "blocked_task", "customer_operator_evidence", "policy_change", "missing_integration", "measured_performance_gap"]), evidenceIds: z.array(z.string().min(1).max(160)).min(1), frequency: z.number().int().min(1).max(100000), severity: z.enum(["low", "medium", "high", "critical"]) }).strict(), affected: LinkSchema, reuseDecision: z.object({ decision: z.enum(["reuse", "upgrade", "create"]), searches: z.array(z.object({ source: z.enum(["local_registry", "transactional_ledger", "graph_projection", "authorized_vector_index"]), query: z.string().min(2).max(400), resultRefs: z.array(z.string().max(240)).max(20) }).strict()).length(4), whyReuseUnsuitable: z.string().max(1200).default("") }).strict(), dependencies: z.array(z.string().max(300)).max(30), permissions: z.array(z.string().max(160)).max(30), data: z.string().min(3).max(1000), infrastructure: z.string().min(3).max(1000), risks: z.object({ licence: z.string().min(2).max(600), security: z.string().min(2).max(600), privacy: z.string().min(2).max(600) }).strict(), cost: z.object({ implementationUsd: z.number().min(0), operatingUsdMonthly: z.number().min(0), basis: z.string().min(2).max(400) }).strict(), acceptanceTests: z.array(z.string().min(3).max(800)).min(1).max(20), metrics: z.array(z.string().min(3).max(400)).min(1).max(20), rollout: z.string().min(3).max(1000), monitoring: z.string().min(3).max(1000), rollback: z.string().min(3).max(1000), ownerApprovalRequired: z.literal(true), deduplication: z.object({ key: z.string().min(8).max(240), method: z.literal("deterministic-token-jaccard/v1"), modelVersion: z.string().min(1).max(120), threshold: z.number().min(0).max(1) }).strict(), modelRationale: z.string().max(2000).default("") }).strict();

export class SuggestionIntelGovernance {
  constructor({ store } = {}) { if (!store) throw new Error("Suggestion/Intel governance requires Decision Continuity."); this.store = store; }
  async createSuggestion(input, { tenantId, workspaceId = "default", actor } = {}) {
    const parsed = SuggestionSchema.parse(input);
    return this.store.mutate((state, events) => {
      ensure(state); const trigger = Object.values(state.processedConditionEvents).find((item) => item.tenantId === tenantId && item.workspaceId === workspaceId && (item.eventId === parsed.triggeringEventId || item.idempotencyKey === parsed.triggeringEventId));
      if (!trigger) throw new DecisionContinuityError("Suggestions require a trusted, tenant-scoped condition event.", { code: "trigger_not_found", status: 409 });
      const branch = parsed.affected.branchId ? state.branches[parsed.affected.branchId] : null; if (parsed.affected.branchId) scope(branch, tenantId, workspaceId);
      const existing = Object.values(state.governedSuggestions).find((item) => item.tenantId === tenantId && item.workspaceId === workspaceId && item.deduplication.key === parsed.deduplication.key && ACTIVE.has(item.state));
      if (existing) return { status: "deduplicated", suggestion: copy(existing) };
      const stateName = new Date(parsed.expiresAt) <= new Date() ? "expired" : parsed.remainingBlockers.length ? "needs_evidence" : "ready_for_review";
      const record = { id: id("suggestion"), schemaVersion: "suggestion-intel/v1", tenantId, workspaceId, ...parsed, modelRationale: safeText(parsed.modelRationale), authoritativeFacts: { triggerEventId: parsed.triggeringEventId, evidenceIds: parsed.triggeringEvidenceIds, branchId: parsed.affected.branchId || null }, state: stateName, policyState: "not_evaluated", revisions: [{ revision: 1, actorId: actor.id, reason: "created", contentDigest: digest(parsed), at: now() }], lifecycleLinks: [], createdAt: now(), updatedAt: now(), revision: 1 };
      state.governedSuggestions[record.id] = record; events.push(audit({ tenantId, workspaceId, type: "suggestion.created", actor, correlationId: parsed.affected.qagentRunId || parsed.affected.brainxRouteId, payload: { suggestionId: record.id, triggerEventId: parsed.triggeringEventId, branchId: record.affected.branchId || null, state: record.state, deduplication: record.deduplication } })); return { status: "created", suggestion: copy(record) };
    });
  }
  async editSuggestion({ suggestionId, patch, reason }, { tenantId, workspaceId = "default", actor } = {}) {
    const parsed = SuggestionSchema.parse(patch); if (!reason || String(reason).trim().length < 3) throw new DecisionContinuityError("An edit reason is required.", { code: "edit_reason_required" });
    return this.store.mutate((state, events) => { ensure(state); const record = state.governedSuggestions[suggestionId]; scope(record, tenantId, workspaceId); const before = digest({ ...record, revisions: undefined }); const after = digest(parsed); const invalidated = before !== after; Object.assign(record, parsed, { modelRationale: safeText(parsed.modelRationale), state: parsed.remainingBlockers.length ? "needs_evidence" : "ready_for_review", policyState: invalidated ? "invalidated" : record.policyState, evaluationDigest: invalidated ? null : record.evaluationDigest || null, approvalDigest: invalidated ? null : record.approvalDigest || null, updatedAt: now(), revision: record.revision + 1 }); record.revisions.push({ revision: record.revision, actorId: actor.id, reason: safeText(reason, 600), contentDigest: after, invalidatedEvaluationApproval: invalidated, at: now() }); events.push(audit({ tenantId, workspaceId, type: "suggestion.edited", actor, payload: { suggestionId, invalidated } })); return copy(record); });
  }
  async reviewSuggestion({ suggestionId, decision, evaluationDigest = null, approvalDigest = null, reason = "" }, { tenantId, workspaceId = "default", actor } = {}) {
    return this.store.mutate((state, events) => { ensure(state); const record = state.governedSuggestions[suggestionId]; scope(record, tenantId, workspaceId); if (decision === "rejected") record.state = "rejected"; else if (decision === "ready_for_approval") { if (record.remainingBlockers.length) throw new DecisionContinuityError("Remaining blockers prevent execution readiness.", { code: "remaining_blockers", status: 409 }); if (!evaluationDigest) throw new DecisionContinuityError("Independent evaluation evidence is required.", { code: "evaluation_required", status: 409 }); record.state = "ready_for_approval"; record.evaluationDigest = evaluationDigest; record.policyState = "evaluated"; } else throw new DecisionContinuityError("Unsupported suggestion review decision.", { code: "invalid_review" }); record.updatedAt = now(); record.revision += 1; events.push(audit({ tenantId, workspaceId, type: "suggestion.reviewed", actor, payload: { suggestionId, decision: record.state, reason: safeText(reason, 600), approvalDigest } })); return copy(record); });
  }
  async linkGovernedPromotion({ suggestionId, promotionRequestId, approvalDigest }, { tenantId, workspaceId = "default", actor } = {}) { if (!promotionRequestId || !approvalDigest) throw new DecisionContinuityError("A Step 4 governed promotion request and human approval digest are required.", { code: "promotion_request_required" }); return this.store.mutate((state, events) => { ensure(state); const record = state.governedSuggestions[suggestionId]; scope(record, tenantId, workspaceId); if (record.revisions[0]?.actorId === actor.id) throw new DecisionContinuityError("The suggestion originator cannot approve its lifecycle entry.", { code: "separation_of_duties_denied", status: 403 }); if (record.remainingBlockers.length || record.state !== "ready_for_approval") throw new DecisionContinuityError("Only blocker-free, independently evaluated suggestions may enter Step 4.", { code: "lifecycle_entry_denied", status: 409 }); record.state = "approved_for_execution"; record.approvalDigest = approvalDigest; record.lifecycleLinks.push({ kind: "governed_promotion", promotionRequestId, linkedBy: actor.id, at: now(), executionAuthority: "Step 4 policy, human approval, canary, and rollback remain required" }); record.updatedAt = now(); record.revision += 1; events.push(audit({ tenantId, workspaceId, type: "suggestion.governed_promotion_linked", actor, payload: { suggestionId, promotionRequestId } })); return copy(record); }); }
  async createIntelProposal(input, { tenantId, workspaceId = "default", actor } = {}) { const parsed = IntelSchema.parse(input); if (parsed.reuseDecision.decision === "create" && !parsed.reuseDecision.whyReuseUnsuitable.trim()) throw new DecisionContinuityError("Create decisions must preserve why reuse or upgrade is unsuitable.", { code: "reuse_rationale_required" }); return this.store.mutate((state, events) => { ensure(state); if (parsed.affected.branchId) scope(state.branches[parsed.affected.branchId], tenantId, workspaceId); const duplicate = Object.values(state.intelCapabilityProposals).find((item) => item.tenantId === tenantId && item.workspaceId === workspaceId && item.deduplication.key === parsed.deduplication.key && ACTIVE.has(item.state)); if (duplicate) return { status: "deduplicated", proposal: copy(duplicate) }; const proposal = { id: id("intel_capability"), schemaVersion: "intel-capability-proposal/v1", tenantId, workspaceId, ...parsed, modelRationale: safeText(parsed.modelRationale), authoritativeFacts: { trigger: parsed.trigger, reuseSearches: parsed.reuseDecision.searches }, state: "ready_for_review", policyState: "not_evaluated", lifecycleLinks: [], createdAt: now(), updatedAt: now(), revision: 1 }; state.intelCapabilityProposals[proposal.id] = proposal; events.push(audit({ tenantId, workspaceId, type: "intel.capability_proposed", actor, correlationId: parsed.affected.qagentRunId || parsed.affected.brainxRouteId, payload: { proposalId: proposal.id, trigger: proposal.trigger, reuseDecision: proposal.reuseDecision.decision, deduplication: proposal.deduplication } })); return { status: "created", proposal: copy(proposal) }; }); }
  async list({ tenantId, workspaceId, kind = "suggestions" } = {}) { const state = await this.store.readState(); const source = kind === "intel" ? state.intelCapabilityProposals || {} : state.governedSuggestions || {}; return Object.values(source).filter((item) => item.tenantId === tenantId && (!workspaceId || item.workspaceId === workspaceId)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).map(copy); }
}
